using System.Collections.Generic;

namespace ControlAgentNet.Core.Models;

/// <summary>
/// Status of the current interaction turn.
/// </summary>
public enum ExecutionStatus
{
    Running,
    AwaitingApproval,
    Denied,
    Completed,
    Faulted
}

/// <summary>
/// Contextual metadata passed through the agent middleware pipeline.
/// Wraps the incoming message and allows middlewares to attach extra state.
/// </summary>
public sealed class AgentContext
{
    public required IncomingMessage Message { get; init; }

    /// <summary>
    /// Arbitrary key-value metadata that middlewares can attach and read.
    /// Useful for passing data between middlewares without coupling them.
    /// </summary>
    public Dictionary<string, object?> Items { get; } = new();

    /// <summary>
    /// A list of "internal thoughts" and tool calls generated by the engine.
    /// Useful for 'Inner Monologue' dashboard visualization.
    /// </summary>
    public List<AgentThought> Thoughts { get; } = new();

    /// <summary>
    /// Cumulative token usage for this interaction turn. 
    /// Used by Budgeting Middlewares.
    /// </summary>
    public TokenUsage? Usage { get; set; }

    /// <summary>
    /// The current state of the execution flow. 
    /// Can be changed by middlewares to pause the agent for 'Human-in-the-loop' scenarios.
    /// </summary>
    public ExecutionStatus Status { get; set; } = ExecutionStatus.Running;

    /// <summary>
    /// If Status is AwaitingApproval, this identifies the specific request for the human.
    /// </summary>
    public string? ApprovalRequestId { get; set; }
}

public sealed record AgentThought(string Type, string Content, DateTimeOffset Timestamp)
{
    public string Id { get; init; } = Guid.NewGuid().ToString("N");
    public string? ParentId { get; init; }
}

public sealed record TokenUsage(int PromptTokens, int CompletionTokens)
{
    public int TotalTokens => PromptTokens + CompletionTokens;
}
